CREATE OR REPLACE PACKAGE PKG_CRUD_HOSPITAL AS
    --CRUD
    PROCEDURE INSERT_HOSPITAL(P_NOMBRE IN HOSPITAL.NOMBRE%TYPE, 
                                    P_ANTIGUEDAD IN HOSPITAL.ANTIGUEDAD%TYPE,
                                    P_AREA IN HOSPITAL.AREA%TYPE,
                                    P_FECHAREGISTRO IN HOSPITAL.FECHAREGISTRO%TYPE,
                                    P_IDDISTRITO IN HOSPITAL.IDDISTRITO%TYPE,
                                    P_IDSEDE IN HOSPITAL.IDSEDE%TYPE,
                                    P_IDGERENTE IN HOSPITAL.IDGERENTE%TYPE,
                                    P_IDCONDICION IN HOSPITAL.IDCONDICION%TYPE,
                                    P_MENSAJE OUT VARCHAR2);
    PROCEDURE DELETE_HOSPITAL(P_IDHOSPITAL IN HOSPITAL.IDHOSPITAL%TYPE,
                                    P_MENSAJE OUT VARCHAR2);
    PROCEDURE UPDATE_HOSPITAL(P_IDHOSPITAL IN HOSPITAL.IDHOSPITAL%TYPE,
                                    P_NOMBRE IN HOSPITAL.NOMBRE%TYPE, 
                                    P_ANTIGUEDAD IN HOSPITAL.ANTIGUEDAD%TYPE,
                                    P_AREA IN HOSPITAL.AREA%TYPE,
                                    P_FECHAREGISTRO IN HOSPITAL.FECHAREGISTRO%TYPE,
                                    P_IDDISTRITO IN HOSPITAL.IDDISTRITO%TYPE,
                                    P_IDSEDE IN HOSPITAL.IDSEDE%TYPE,
                                    P_IDGERENTE IN HOSPITAL.IDGERENTE%TYPE,
                                    P_IDCONDICION IN HOSPITAL.IDCONDICION%TYPE,
                                    P_MENSAJE OUT VARCHAR2);
    --BUSQUEDAS
    PROCEDURE HOSPITAL_FIND_BY_ID(P_IDHOSPITAL IN HOSPITAL.IDHOSPITAL%TYPE,
                                    P_CURSOR_HOSPITAL OUT SYS_REFCURSOR);
    PROCEDURE HOSPITAL_FIND_ALL(P_CURSOR_HOSPITALES OUT SYS_REFCURSOR);
    PROCEDURE HOSPITAL_FIND_BY_NOMBRE(P_NOMBRE IN HOSPITAL.NOMBRE%TYPE,
                                    P_CURSOR_HOSPITALES_NOMBRE OUT SYS_REFCURSOR);
    PROCEDURE HOSPITAL_FIND_BY_SEDE(P_IDSEDE IN HOSPITAL.IDSEDE%TYPE,
                                    P_CURSOR_HOSPITALES_SEDE OUT SYS_REFCURSOR);
END PKG_CRUD_HOSPITAL;